// Seed data for BDM Rollouts & Deliverables.
// Each section has a number, title, and array of task text lines.
// Sub-headings within a section are represented as { heading: "..." } entries.

export const BDM_SEED_SECTIONS = [
  {
    number: 1,
    title: "Business restructure, rebrand and administration",
    tasks: [
      "Rebrand/restructure STS under the Alliance banner.",
      "Confirm final company/division naming convention across all systems and documents.",
      "Rebrand business documentation, portals, emails and customer-facing material.",
      "Establish a cleaner organisational structure before the new administration/accounts support person commences.",
      "Restructure accounts into two defined functions: Accounts Payable and Accounts Receivable.",
      { heading: "Develop measurable KPIs/incentives for Accounts Receivable based on:" },
      "Outstanding debt recovery.",
      "Payment commitments obtained.",
      "Weekly/monthly debtor performance.",
      { heading: "Develop measurable KPIs/incentives for Accounts Payable based on:" },
      "Supplier negotiations.",
      "Deferred payment arrangements.",
      "Cost reductions/credits.",
      "Maintaining supplier continuity.",
      "Review/restructure the Xero accounting environment.",
      "Confirm BAS workflow: Internal accounts team prepares all records; BAS/tax agent reviews and lodges.",
      "Bring all bank reconciliations fully up to date.",
      "Ensure all receipts/invoices/payments are correctly entered.",
      "Clean up all customer records.",
      "Clean up all supplier records.",
      "Verify costing across customers, suppliers, stock and transactions.",
      "Develop a plan to clear/regularise outstanding local supplier accounts.",
      "Confirm funding/payment arrangements discussed regarding the broader restructure.",
    ],
  },
  {
    number: 2,
    title: "System access, email and security clean-up",
    tasks: [
      "Consolidate company email accounts under the new group structure.",
      "Eliminate unnecessary duplicate STS/Alliance portal logins.",
      "Give each employee one clearly controlled company identity/login wherever practical.",
      "Review all existing user access to business systems.",
      "Remove former employee/contractor access.",
      "Reset passwords and access credentials associated with old accounts.",
      "Review Sienna's previous STS Hub and Alliance credentials.",
      "Determine whether the old STS Hub account remains accessible.",
      "Review system session/activity logs associated with Adrian.",
      "Investigate access recorded against Sienna's account while she was absent.",
      "Review the unexplained PO number gap between PO0235 and PO0238.",
      "Specifically investigate the creation/activity relating to PO0237.",
      "Determine whether purchase orders can be deleted and whether any were deleted.",
      "Audit supplier records that appear to have been manually typed rather than selected from the database.",
      "Review activity on 7-10 August for suspicious or unexplained transactions.",
      { heading: "Review affected quotes identified during the discussion, including:" },
      "Q-053.",
      "Q-054.",
      "Q-087.",
      "Q-032.",
      "Review sales-order numbering/date gaps.",
      "Review invoice numbering/date gaps.",
      "Complete outstanding invoices currently awaiting processing.",
      "Ensure invoice creation dates reflect the correct underlying transaction dates where appropriate.",
      "Create an internal access-control/offboarding procedure to prevent a repeat of the access issue.",
    ],
  },
  {
    number: 3,
    title: "Inventory and parts-system clean-up",
    tasks: [
      "Complete a physical stock reconciliation against the system.",
      "Review all TotalEnergies-loaded part numbers.",
      "Confirm each part number matches the correct product.",
      "Confirm correct product descriptions.",
      "Correct incorrect equipment classifications.",
      "Correct incorrect product categories.",
      "Correct incorrect pack sizes/volumes.",
      "Correct 205 L / 208 L discrepancies.",
      "Confirm unit cost for every stocked product.",
      "Confirm retail selling price for every stocked product.",
      "Confirm commercial selling price for every stocked product.",
      "Confirm price-per-litre calculations.",
      "Confirm price-per-pack calculations.",
      "Confirm current stock quantities.",
      "Set minimum stock quantities.",
      "Correct combined litre calculations where different pack sizes exist.",
      "Remove/deactivate duplicate product records.",
      "Add missing stock items that have not yet been entered.",
      "Review Rubia Works product records.",
      "Review Quartz product records.",
      "Review Azolla/Azola product records.",
      "Review Multis grease cartridge records.",
      "Review Fluidmatic records.",
      "Review TransTech records.",
      "Review Cool Elf records.",
      "Review Dynatrans records.",
      "Review Glacelf records.",
      { heading: "Ensure grease is represented correctly by:" },
      "Individual cartridge quantity.",
      "Box quantity.",
      "Cost per cartridge.",
      "Retail price.",
      "Commercial price.",
      "Correct stock record discussed for approximately 48 grease cartridges.",
      "Review minimum-stock methodology for cartons/boxes versus individual units.",
      "Confirm commercial-customer pricing logic throughout the parts catalogue.",
      { heading: "Required portal/software changes" },
      "Add ability to mark parts Active / Inactive.",
      "Allow a completed/started stocktake to be reopened.",
      "Allow users to re-enter and amend an existing stocktake.",
      "Fix Admin/Document Settings so changes actually save.",
      "Allow authorised administrators to edit: Statements, Terms, Notes, Remarks, Document wording, and other configurable documentation.",
      "Review product-category architecture so oils are not incorrectly classified as vehicle/equipment types.",
      "Establish proper customer classification for retail versus commercial customers.",
    ],
  },
  {
    number: 4,
    title: "Premises - basic building works",
    tasks: [
      { heading: "Walls" },
      "Purchase additional compound/topper.",
      "Fill holes and damaged wall areas.",
      "Sand repaired walls.",
      "Purchase additional primer.",
      "Purchase required paint.",
      "Paint warehouse/showroom walls bright white where specified.",
      "Paint internal office areas black where specified.",
      "Paint external face of office black.",
      "Paint reception feature wall black.",
      "Prepare, plaster, prime and paint Priority Parts rooms.",
      "Paint exterior areas black/grey as discussed.",
      "Obtain all painting material and labour quotes.",
      { heading: "Flooring" },
      "Obtain quote for epoxy flooring.",
      "Determine final epoxy finish.",
      "Determine green fleck/accent treatment.",
      "Confirm areas receiving epoxy.",
      "Confirm floor preparation requirements.",
      "Confirm final installation cost.",
      { heading: "Windows" },
      "Send existing window measurements to C Signs.",
      "Obtain window tint/wrap/frosting quote.",
      "Tint office/reception glazing sufficiently for privacy.",
      "Apply grey/dark frosting treatment with stencil/cut-out design where specified.",
      "Completely black out hallway windows between the rear entrance and office.",
      "Completely black out relevant double-door glazing.",
      "Add branding/directional signage to the double doors.",
    ],
  },
  {
    number: 5,
    title: "Reception and main office",
    tasks: [
      { heading: "Reception" },
      "Finalise reception desk design.",
      "Arrange manufacture/supply/install of reception counter.",
      "Install Alliance Priority Parts branding on reception counter.",
      "Confirm secondary wording, proposed as: Alliance Priority Parts. A division of Malian Industry Group / Malian Industry Partners.",
      "Finalise exact division wording before fabrication.",
      "Install large Alliance \"A\" wall logo.",
      "Install secondary \"A\" logo on reception counter.",
      "Install internal directional signage.",
      "Install front entry/office signage.",
      "Install green feature/neon/LED lighting.",
      "Install reception chairs.",
      "Provide two front-desk computer workstations.",
      "Provide required monitors.",
      "Provide POS/EFTPOS equipment.",
      "Install concealed printer in the identified position beside the office/reception area.",
      { heading: "Internal office" },
      "Paint complete internal office black.",
      "Install Mitchell's main desk.",
      "Install Sienna's smaller/internal desk.",
      "Install computer/monitor setup for both positions.",
      "Install large bookshelf against rear wall below the air-conditioning.",
      "Install concrete-look architectural sheeting.",
      "Install selected wall cladding.",
      "Clad around the air-conditioning area.",
      "Clad above office windows.",
      "Clad specified full-height wall sections.",
      "Install two-seat lounge/meeting seating.",
      "Install required cameras.",
      "Install swipe-card access to office.",
    ],
  },
  {
    number: 6,
    title: "Architectural cladding and branding",
    tasks: [
      "Finalise cladding specification. Current preferred option from the discussion: Birch.",
      "Confirm Birch before purchasing.",
      "Measure the complete required cladding area.",
      "Measure reception/priority-parts wall.",
      "Measure double-door sections.",
      "Measure tapered cladding sections.",
      "Measure office internal cladding.",
      "Measure sections around air-conditioning.",
      "Measure areas above windows.",
      "Measure concrete-look sheeting areas.",
      "Calculate number of 2.9 m cladding lengths required.",
      "Minimise waste/offcuts in cladding layout.",
      "Obtain supplier quote for total cladding quantity.",
      "Install cladding across Priority Parts wall.",
      "Conceal double doors within cladding treatment where designed.",
      "Create tapered/angled cladding transition.",
      "Apply textured black finish to exposed areas.",
      "Incorporate green backlighting/underglow behind cladding.",
      "Develop 3D/stand-off Alliance logo treatment.",
      "Confirm whether logo is internally illuminated, backlit or separately illuminated.",
      "Produce final visual/mock-up before fabrication.",
      "Build stainless/brushed-metal supplier partnership signage.",
      "Include relevant partner brands such as TotalEnergies, Würth, Power Crank etc. subject to final approval.",
    ],
  },
  {
    number: 7,
    title: "Priority Parts rooms - physical fit-out",
    tasks: [
      { heading: "For each Priority Parts room/bay:" },
      "Install pegboard on one wall.",
      "Install small storage tubs beneath pegboard.",
      "Install low-level heavy-duty shelving.",
      "Allow for approximately five or more large tubs at floor level where practical.",
      "Install approximately 300 mm deep shelving above.",
      "Extend shelving vertically toward roof height.",
      "Install heavy-duty hanging rails/brackets.",
      { heading: "Provide hanging storage for:" },
      "Belts.",
      "Chains.",
      "Service kits.",
      "Hoses.",
      "Long/bulky parts.",
      { heading: "Provide shelf storage for:" },
      "Alternators.",
      "Compressors.",
      "Condensers.",
      "Fan motors.",
      "Filters.",
      "Smaller boxed components.",
      { heading: "Provide floor/tub storage for:" },
      "Brake components.",
      "Boosters.",
      "Slack adjusters.",
      "S-cams.",
      "Hubs.",
      "Bearings.",
      "Other heavy components.",
      { heading: "Install small-bin storage for:" },
      "Bulbs.",
      "Electrical pieces.",
      "Clips.",
      "Bolts.",
      "Relays.",
      "Solenoids.",
      "Fuse kits.",
      "Radiator caps.",
      "Other loose parts.",
      "Provide a small dangerous-goods cabinet.",
      "Provide a mobile service trolley for each room where feasible.",
      "Consider overhead/lightweight storage.",
      "Install Priority Room identification signage.",
      "Determine bay numbering, e.g. B1, B2, B3, B4.",
      "Install access-control reader.",
      "Install CCTV camera facing entry.",
      "Install required alarm/security systems.",
    ],
  },
  {
    number: 8,
    title: "Main warehouse / spare-parts area",
    tasks: [
      "Procure pallet racking/heavy-duty shelving.",
      "Procure universal/light-duty shelving.",
      "Retain/integrate existing Würth stand.",
      "Procure pegboard.",
      "Install pegboard on brick wall.",
      "Install pegboard on ends of racking.",
      "Install pegboard along long rear/side wall.",
      "Install pegboard above dispatch area.",
      "Install lower shelving beneath pegboard.",
      "Establish dedicated consumables aisles.",
      "Establish Würth-branded consumables area.",
      "Establish secondary consumables brand area.",
      "Create pigeon-hole storage.",
      "Create heavy-parts storage area.",
      "Create filter/component storage.",
      "Create bulky-component storage.",
      "Create oil storage for 20 L and smaller containers.",
      { heading: "Install cupboards/storage for:" },
      "Boxes.",
      "Bags.",
      "Packaging.",
      "Air fresheners.",
      "Business consumables.",
      { heading: "Dispatch area" },
      "Install stainless-steel dispatch bench.",
      "Establish goods-receiving/stock-entry workstation.",
      "Set up labelling station.",
      "Provide labels and label printer.",
      "Provide packaging/boxes.",
      "Install dispatch computer/laptop.",
      "Create dedicated STS Workshop Dispatch section.",
      "Establish three-tier dispatch shelving.",
      "Create dispatch-receipt process.",
      "Require quantity confirmation at collection.",
      "Require recipient acknowledgement.",
      "Mark items collected/dispatched in system.",
      "Ensure invoicing closes the transaction.",
      { heading: "Rear parts counter" },
      "Install pedestal/service desk at rear parts entrance.",
      "Install laptop/computer.",
      "Install service bell/call mechanism.",
      "Establish controlled staff-only access behind counter.",
      "Enable parts to be invoiced/marked collected directly from this workstation.",
    ],
  },
  {
    number: 9,
    title: "After-hours / 24-7 Priority Parts operating system",
    tasks: [
      "Install permanently powered tablet/check-in terminal.",
      "Build customer/company selection interface.",
      "Allow scheduled collection to pre-populate authorised user.",
      "Allow unscheduled authorised collector identification.",
      "Record collector name.",
      "Record/photo-match authorised user's identity.",
      "Automatically notify staff when someone checks in.",
      "Generate temporary/access code where applicable.",
      "Connect access workflow to door-control system.",
      "Record room entry time.",
      "Record room exit time.",
      "Require user to confirm door has been closed.",
      "Require collection completion acknowledgement.",
      "Provide on-call assistance button/phone number.",
      "Record additional/unscheduled parts removed.",
      "Automatically flag stock requiring replenishment.",
      "Create audit trail against customer and individual user.",
      "Link access timestamps with CCTV records.",
      "Ensure unauthorised parts taken by an authorised person can be traced and invoiced.",
      "Develop after-hours terms/user agreement.",
      { heading: "Customer Priority Parts portal" },
      "Build client portal for each participating company.",
      "Display authorised personnel.",
      "Store user ID/photo.",
      "Store emergency contacts.",
      "Store authorised access areas.",
      "Store access codes where applicable.",
      "Display managed stock.",
      "Allow customer to request additional parts.",
      "Display current stock quantities.",
      "Produce usage/movement reports.",
      "Identify slow-moving stock.",
      "Allow stock substitution/buy-back discussions.",
      "Record weekly stocktake.",
      "Notify customer of stocktake results.",
      "Perform post-collection stock reconciliation.",
      "Trigger replenishment orders.",
      "Invoice generic consumables removed.",
      "Distinguish: Everyday/general inventory and Customer-funded critical stock.",
    ],
  },
  {
    number: 10,
    title: "Access control and physical security",
    tasks: [
      { heading: "Northwest Comms quote" },
      "Request complete access-control proposal from Northwest Comms.",
      "Confirm card-reader compatibility across multiple doors.",
      "Confirm individual cards can have different access permissions.",
      "Confirm time-limited access.",
      "Confirm expiry dates can be assigned.",
      "Confirm cards can be cancelled remotely.",
      "Confirm lost cards can be immediately disabled.",
      "Confirm access reports can be exported.",
      "Confirm card activity can be matched to CCTV.",
      "Confirm alarm integration.",
      "Confirm remote alarm activation functionality.",
      { heading: "Swipe-controlled doors (approximately 8 controlled access points — confirm before quote)" },
      "Main/front entrance.",
      "Main office.",
      "Rear door into parts warehouse.",
      "Priority Parts Bay 1.",
      "Priority Parts Bay 2.",
      "Priority Parts Bay 3.",
      "Priority Parts Bay 4.",
      "Hydraulics/oil room.",
      "Confirm whether any staff-only internal door needs an additional reader.",
      "Install physical security bar on rear restricted parts access.",
      "Install magnetic alarm sensor on restricted door.",
      "Configure alarm if secured door is forced.",
      "Install appropriate external/security lighting.",
      { heading: "Access cards" },
      "Obtain card costs.",
      "Brand/sticker customer access cards.",
      "Issue individual cards rather than shared credentials.",
      "Require personal identification for every authorised cardholder.",
      "Develop access-card user agreement.",
      "Record card number against individual.",
      "Establish card expiry/review process.",
      "Establish lost-card replacement process.",
      "Establish revocation process.",
      "Finalise proposed card subscription charge (discussion proposed $25 per card per user per month).",
      "Finalise replacement/re-establishment fee.",
      "Determine maximum cards per Priority Parts customer/bay.",
    ],
  },
  {
    number: 11,
    title: "CCTV",
    tasks: [
      "Obtain Northwest Comms CCTV quote.",
      "Confirm system supports remote viewing.",
      "Confirm recording retention requirements.",
      "Link access-event timestamps to CCTV.",
      { heading: "Target approximately 16 cameras:" },
      "One camera in each of four Priority Parts bays.",
      "Two cameras covering the main reception/entrance.",
      "Hallway/reception-area camera.",
      "Parts-area/dispatch camera.",
      "Rear service/pedestal entrance coverage.",
      "Exterior front-facing camera.",
      "Exterior rear/end-of-awning coverage.",
      "Oil/hydraulics exterior coverage.",
      "Oil/hydraulics internal coverage.",
      "Main office camera.",
      "Mitchell's office camera.",
      "Confirm remaining angles required to reach final 16-camera layout.",
      "Produce camera-position plan before installation.",
    ],
  },
  {
    number: 12,
    title: "Phones, Wi-Fi and communications",
    tasks: [
      "Engage Northwest Comms to complete communications setup.",
      "Extend Wi-Fi into oil/hydraulics room.",
      "Extend Wi-Fi into external/donga office.",
      "Install/configure cloud-phone system.",
      { heading: "Provide approximately 9 phones:" },
      "Two at front/reception.",
      "Two in main office.",
      "One at rear service counter.",
      "One at dispatch.",
      "Two in external/donga office.",
      "One in hydraulics room.",
      "Confirm landline/cloud-phone numbers.",
      "Establish after-hours contact number.",
      "Configure call routing/on-call arrangements.",
    ],
  },
  {
    number: 13,
    title: "Lunchroom/staff area",
    tasks: [
      "Install fridge.",
      "Install microwave.",
      "Install shelf/storage.",
      "Install hooks/hanging area for jackets.",
      "Install bar/bench-style lunch counter.",
      "Purchase/install 2-3 stools.",
      "Install TV/display.",
      "Include CCTV/reception view on screen where practical.",
      "Install curtain/privacy treatment.",
      "Ensure air-conditioning remains unobstructed.",
    ],
  },
  {
    number: 14,
    title: "Exterior, oil and hydraulics infrastructure",
    tasks: [
      "Measure proposed rear concrete area.",
      "Obtain concrete quote.",
      "Create rough/blinding concrete slab rather than polished slab.",
      "Current concept requires roughly 1.5 m projection along the rear section.",
      "Extend concrete around side areas as discussed.",
      "Confirm approximately 2 m additional return area where required.",
      "Produce final dimensional plan before quoting.",
      "Provide space for four IBC/pods.",
      "Install four IBC oil storage positions.",
      "Design/install awning over oil storage.",
      "Install four oil pumps.",
      "Route oil lines from IBCs into oil room.",
      "Locate air compressor externally.",
      "Provide concrete base for compressor.",
      "Connect compressor supply into building.",
      "Source/install proposed 20-foot container.",
      "Confirm container position relative to existing 10-foot unit.",
      "Ensure sufficient access around compressor/container.",
      "Install swipe access to hydraulics/oil room.",
      "Provide external customer oil-storage cages where required.",
      "Provide separate PIN-code locks for external cages.",
      "Allocate cages to individual commercial customers where appropriate.",
    ],
  },
  {
    number: 15,
    title: "External presentation",
    tasks: [
      "Paint exterior black/grey.",
      "Obtain planter-box quote.",
      "Install front building signage.",
      "Install Entry / Office directional signage.",
      "Finalise exterior Alliance branding.",
      "Take updated photographs of external areas for planning/design.",
      "Review external lighting requirements.",
    ],
  },
  {
    number: 16,
    title: "Supplier database and procurement records",
    tasks: [
      { heading: "For every supplier:" },
      "Verify legal/trading name.",
      "Enter primary contact.",
      "Enter accounts contact.",
      "Enter phone numbers.",
      "Enter email addresses.",
      "Enter correct physical/postal address.",
      "Enter supplier account number.",
      "Enter bank account name.",
      "Enter BSB.",
      "Enter bank account number.",
      "Enter approved credit limit.",
      "Enter payment terms.",
      "Enter current account status.",
      "Record amount currently owing where applicable.",
      "Record whether account is on stop/on hold.",
      "Send supplier account information/application form where details are missing.",
      "Search existing emails first for required information.",
      "Upload completed supplier documentation back to supplier record.",
      "Match supplier information with Xero.",
      "Complete Xero matching/manual entry as required.",
      "Complete procurement notes.",
      "Add pricing notes.",
      "Add freight notes.",
      "Add account-risk notes.",
      "Add reliability/performance notes.",
      "Record whether supplier is preferred.",
      "Record warranty support.",
      "Record returns policy/returns accepted.",
      "Correct supplier product/category coverage.",
      "Enter sales territory.",
      "Store supplier portal URL.",
      "Store appropriate portal-login reference/access details securely.",
      "Correct TotalEnergies classification primarily to oils/lubricants rather than irrelevant equipment categories.",
    ],
  },
  {
    number: 17,
    title: "Quotes and costing package (RFQ register)",
    tasks: [
      "Convert all line items below into a formal RFQ register.",
      "Wall preparation materials.",
      "Primer.",
      "Paint.",
      "Painting labour.",
      "Epoxy flooring.",
      "Window tint/frosting/wrap.",
      "Internal signage.",
      "External signage.",
      "3D Alliance signage.",
      "Cladding.",
      "Concrete-look sheeting.",
      "Green feature lighting.",
      "Reception desk.",
      "Office desks.",
      "Office chairs.",
      "Lounge.",
      "Bookshelf/storage.",
      "Pallet racking.",
      "Heavy-duty shelving.",
      "Light-duty shelving.",
      "Pegboard.",
      "Plastic parts bins.",
      "Large storage tubs.",
      "Hanging rails.",
      "Dangerous-goods cabinets.",
      "Service trolleys.",
      "Stainless dispatch bench.",
      "Computers.",
      "Monitors.",
      "Tablets/laptops.",
      "Printer/label equipment.",
      "CCTV.",
      "Swipe-card access.",
      "Access cards.",
      "Alarm system.",
      "Wi-Fi extension.",
      "Cloud phones.",
      "Concrete works.",
      "Awning.",
      "Oil pumps/plumbing.",
      "Compressor installation.",
      "20-foot container.",
      "Planter boxes.",
      "Exterior lighting.",
    ],
  },
  {
    number: 18,
    title: "Measurement package",
    tasks: [
      { heading: "Sienna" },
      "Complete physical measurements requested for cladding.",
      "Measure Priority Parts/reception wall.",
      "Measure double-door area.",
      "Measure taper points.",
      "Measure office cladding.",
      "Measure around windows.",
      "Measure around air-conditioning.",
      "Measure concrete-look sheeting areas.",
      "Measure pegboard areas.",
      "Measure shelving/racking areas.",
      "Measure rear concrete slab area.",
      "Measure compressor/IBC/container areas.",
      { heading: "Mitchell" },
      "Send Sienna marked-up floor plan.",
      "Put red measurement lines on required areas.",
      "Produce separate measurement markup for cladding.",
      "Produce separate measurement markup for pegboard.",
      "Produce separate measurement markup for concrete.",
      "Produce separate measurement markup for paint/other finishes.",
      "Send design/reference images discussed in meeting.",
      "Send cladding/reception concept images.",
      "Prepare mud map for rear oil/compressor/container layout.",
    ],
  },
  {
    number: 19,
    title: "Development Hub / project-control system",
    tasks: [
      "This is the final container for the entire rollout.",
      "Create Rollout Deliverables section in the business-development/development hub.",
      "Enter every action from this checklist as an individual task.",
      "Assign task owner.",
      "Assign priority.",
      "Assign target completion date.",
      "Add status.",
      "Add notes/remarks.",
      "Attach quote.",
      "Add supplier.",
      "Add purchase link.",
      "Add quoted price.",
      "Add approved price.",
      "Add final cost.",
      "Attach drawings/measurements.",
      "Attach photos.",
      "Record decisions/variations.",
      "Check each deliverable off individually through to 100% shop completion.",
    ],
  },
];