// Icon names, colors, and labels per notification type

export const PRIORITY_CONFIG = {
  low:       { label: "Low",      color: "text-gray-400",   bg: "bg-gray-500/10",   border: "border-gray-500/20"  },
  normal:    { label: "Normal",   color: "text-slate-400",  bg: "bg-slate-500/10",  border: "border-slate-500/20" },
  important: { label: "Important",color: "text-blue-400",   bg: "bg-blue-500/10",   border: "border-blue-500/20"  },
  urgent:    { label: "Urgent",   color: "text-amber-400",  bg: "bg-amber-500/10",  border: "border-amber-500/20" },
  critical:  { label: "Critical", color: "text-red-400",    bg: "bg-red-500/10",    border: "border-red-500/20"   },
};

export const CATEGORY_CONFIG = {
  enquiry:   { label: "Enquiry",   color: "text-blue-400",   bg: "bg-blue-500/15"   },
  breakdown: { label: "Breakdown", color: "text-red-400",    bg: "bg-red-500/15"    },
  quote:     { label: "Quote",     color: "text-purple-400", bg: "bg-purple-500/15" },
  order:     { label: "Order",     color: "text-green-400",  bg: "bg-green-500/15"  },
  inventory: { label: "Inventory", color: "text-amber-400",  bg: "bg-amber-500/15"  },
  purchasing:{ label: "Purchasing",color: "text-cyan-400",   bg: "bg-cyan-500/15"   },
  dispatch:  { label: "Dispatch",  color: "text-indigo-400", bg: "bg-indigo-500/15" },
  finance:   { label: "Finance",   color: "text-emerald-400",bg: "bg-emerald-500/15"},
  credit:    { label: "Credit",    color: "text-yellow-400", bg: "bg-yellow-500/15" },
  admin:     { label: "Admin",     color: "text-gray-400",   bg: "bg-gray-500/15"   },
};

export const TYPE_TO_ICON = {
  enquiry_new: "MessageSquare",
  enquiry_urgent: "AlertTriangle",
  enquiry_assigned: "UserCheck",
  enquiry_updated: "MessageSquare",
  enquiry_converted: "ArrowRight",
  enquiry_waiting: "Clock",
  breakdown_created: "Zap",
  urgent_request: "Zap",
  critical_order: "AlertOctagon",
  quote_new: "FileText",
  quote_assigned: "FileText",
  quote_approved: "CheckCircle",
  quote_expired: "XCircle",
  quote_followup: "Clock",
  order_new: "ShoppingCart",
  order_status: "RefreshCw",
  order_ready_pick: "Package",
  order_partial: "Package",
  order_awaiting_stock: "Clock",
  order_urgent: "Zap",
  order_invoiced: "Receipt",
  stock_low: "TrendingDown",
  stock_out: "AlertTriangle",
  stock_reorder: "RefreshCw",
  stock_adjustment: "BarChart",
  stock_discrepancy: "AlertCircle",
  stock_critical: "AlertOctagon",
  po_created: "ShoppingBag",
  po_overdue: "AlertTriangle",
  po_delayed: "Clock",
  po_received: "CheckCircle",
  po_partial: "Package",
  po_backorder: "Clock",
  po_approval: "UserCheck",
  dispatch_created: "Truck",
  dispatch_ready: "Truck",
  dispatch_packed: "Package",
  dispatch_sent: "Send",
  dispatch_delivered: "CheckCircle",
  dispatch_delayed: "AlertTriangle",
  dispatch_urgent: "Zap",
  invoice_created: "Receipt",
  invoice_emailed: "Mail",
  invoice_overdue: "AlertTriangle",
  credit_limit_exceeded: "AlertOctagon",
  account_on_hold: "Lock",
  payment_received: "DollarSign",
  part_payment: "DollarSign",
  credit_app_uploaded: "Upload",
  credit_app_extracted: "FileSearch",
  credit_app_review: "Eye",
  credit_app_approved: "CheckCircle",
  credit_app_declined: "XCircle",
  credit_app_missing: "AlertCircle",
  task_assigned: "ClipboardList",
  approval_required: "UserCheck",
  template_updated: "FileEdit",
  sync_failure: "WifiOff",
  gmail_sync_failure: "Mail",
  pdf_extraction_failed: "AlertCircle",
  system: "Settings",
};

export const FILTER_TABS = [
  { key: "all",        label: "All" },
  { key: "unread",     label: "Unread" },
  { key: "urgent",     label: "Urgent" },
  { key: "enquiry",    label: "Enquiries" },
  { key: "breakdown",  label: "Breakdown" },
  { key: "order",      label: "Orders" },
  { key: "inventory",  label: "Inventory" },
  { key: "purchasing", label: "Purchasing" },
  { key: "finance",    label: "Finance" },
  { key: "credit",     label: "Credit" },
];