import { useEffect, useRef } from "react";
import { X, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import { COMPANY } from "@/lib/companyDetails";

export default function ReorderPDFModal({ supplier_name, lines, onClose }) {
  const previewRef = useRef(null);

  const subtotal = lines.reduce((s, l) => s + (l.total || l.quantity * l.unit_cost), 0);
  const gst = subtotal * 0.1;
  const total = subtotal + gst;
  const today = new Date().toLocaleDateString("en-AU");

  const generatePDF = () => {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageW = 210;
    const margin = 14;
    const colWidths = [22, 25, 78, 14, 24, 24]; // APP#, Part#, Desc, Qty, Cost, Total
    const colX = [margin];
    colWidths.forEach((w, i) => { if (i > 0) colX.push(colX[i - 1] + colWidths[i - 1]); });

    // Header bar
    doc.setFillColor(20, 20, 20);
    doc.rect(0, 0, pageW, 36, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("PURCHASE ORDER — DRAFT", margin, 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(170, 170, 170);
    doc.text(COMPANY.name.toUpperCase(), margin, 19);
    doc.setFontSize(7);
    doc.text(`${COMPANY.address}, ${COMPANY.city} ${COMPANY.state} ${COMPANY.postcode}`, margin, 24);
    doc.text(`Ph: ${COMPANY.phone}  |  ${COMPANY.email}  |  ${COMPANY.website}`, margin, 29);
    doc.setTextColor(120, 120, 120);
    doc.text(`Date: ${today}`, pageW - margin, 29, { align: "right" });

    // Supplier
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("TO SUPPLIER:", margin, 45);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(supplier_name, margin, 52);
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text("Auto-generated from low stock replenishment", margin, 57);

    // Table header
    let y = 64;
    doc.setFillColor(30, 30, 30);
    doc.rect(margin, y, pageW - margin * 2, 7, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    const headers = ["APP #", "PART #", "DESCRIPTION", "QTY", "UNIT COST", "TOTAL"];
    const aligns = ["left", "left", "left", "center", "right", "right"];
    headers.forEach((h, i) => {
      const x = aligns[i] === "right" ? colX[i] + colWidths[i] - 1 : aligns[i] === "center" ? colX[i] + colWidths[i] / 2 : colX[i] + 1;
      doc.text(h, x, y + 5, { align: aligns[i] });
    });
    y += 7;

    // Table rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    lines.forEach((l, idx) => {
      const rowH = 7;
      if (idx % 2 === 0) {
        doc.setFillColor(248, 248, 248);
        doc.rect(margin, y, pageW - margin * 2, rowH, "F");
      }
      doc.setTextColor(80, 80, 80);
      doc.text(l.app_part_number || "—", colX[0] + 1, y + 5);
      doc.setTextColor(30, 30, 30);
      doc.text(l.part_number || "—", colX[1] + 1, y + 5);
      // Truncate description
      const desc = (l.description || "").substring(0, 42);
      doc.text(desc, colX[2] + 1, y + 5);
      doc.text(String(l.quantity), colX[3] + colWidths[3] / 2, y + 5, { align: "center" });
      doc.text(`$${(l.unit_cost || 0).toFixed(2)}`, colX[4] + colWidths[4] - 1, y + 5, { align: "right" });
      doc.setFont("helvetica", "bold");
      doc.text(`$${(l.total || l.quantity * l.unit_cost || 0).toFixed(2)}`, colX[5] + colWidths[5] - 1, y + 5, { align: "right" });
      doc.setFont("helvetica", "normal");
      // bottom border
      doc.setDrawColor(220, 220, 220);
      doc.line(margin, y + rowH, pageW - margin, y + rowH);
      y += rowH;
    });

    // Totals
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(80, 80, 80);
    doc.text("Subtotal (ex GST)", 135, y);
    doc.text(`$${subtotal.toFixed(2)}`, pageW - margin, y, { align: "right" });
    y += 6;
    doc.text("GST (10%)", 135, y);
    doc.text(`$${gst.toFixed(2)}`, pageW - margin, y, { align: "right" });
    y += 3;
    doc.setFillColor(20, 20, 20);
    doc.rect(130, y, pageW - margin - 130, 10, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("TOTAL (inc GST)", 133, y + 7);
    doc.text(`$${total.toFixed(2)}`, pageW - margin, y + 7, { align: "right" });

    // Footer
    doc.setFillColor(20, 20, 20);
    doc.rect(0, 282, pageW, 15, "F");
    doc.setTextColor(160, 160, 160);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text(`${COMPANY.name}  |  ${COMPANY.address}, ${COMPANY.city} ${COMPANY.state} ${COMPANY.postcode}`, margin, 288);
    doc.text(`Ph: ${COMPANY.phone}  |  ${COMPANY.email}  |  ${COMPANY.website}`, margin, 293);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Alliance Priority Parts ERP", pageW - margin, 290, { align: "right" });

    doc.save(`PO-DRAFT_${supplier_name.replace(/\s+/g, "_")}_${today.replace(/\//g, "-")}.pdf`);
  };

  return (
    <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-2xl rounded-sm shadow-2xl flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-[hsl(0,0%,8%)] px-5 py-3 flex items-center justify-between rounded-t-sm flex-shrink-0">
          <div>
            <h2 className="font-heading text-sm font-bold text-white uppercase tracking-wider">Purchase Order Preview</h2>
            <p className="text-white/50 text-[11px] mt-0.5">{supplier_name}</p>
          </div>
          <button onClick={onClose} className="text-white/60 hover:text-white"><X className="w-5 h-5" /></button>
        </div>

        {/* Preview */}
        <div className="flex-1 overflow-y-auto p-6 bg-gray-100">
          <div className="bg-white rounded shadow-md p-6 max-w-xl mx-auto text-xs text-gray-700 font-mono">
            {/* PO Header */}
            <div className="bg-gray-900 text-white px-4 py-3 rounded-sm mb-4">
              <div className="font-bold text-base tracking-wider">PURCHASE ORDER — DRAFT</div>
              <div className="text-gray-300 text-[11px] font-semibold mt-0.5">ALLIANCE PRIORITY PARTS</div>
              <div className="text-gray-400 text-[9px] mt-1">{COMPANY.address}, {COMPANY.city} {COMPANY.state} {COMPANY.postcode}</div>
              <div className="text-gray-400 text-[9px]">Ph: {COMPANY.phone} · {COMPANY.email} · {COMPANY.website}</div>
              <div className="text-gray-500 text-[9px] mt-1">{today}</div>
            </div>

            <div className="mb-3">
              <div className="text-[9px] text-gray-400 uppercase tracking-wider font-sans mb-0.5">To Supplier</div>
              <div className="font-bold text-sm font-sans">{supplier_name}</div>
              <div className="text-[10px] text-gray-500 font-sans mt-0.5">Auto-generated from low stock replenishment</div>
            </div>

            {/* Lines */}
            <table className="w-full mb-4 border-collapse">
              <thead>
                <tr className="bg-gray-900 text-white text-[9px]">
                  <th className="text-left px-2 py-1">APP #</th>
                  <th className="text-left px-2 py-1">Part #</th>
                  <th className="text-left px-2 py-1">Description</th>
                  <th className="text-center px-2 py-1">Qty</th>
                  <th className="text-right px-2 py-1">Cost</th>
                  <th className="text-right px-2 py-1">Total</th>
                </tr>
              </thead>
              <tbody>
                {lines.map((l, i) => (
                  <tr key={i} className={i % 2 === 0 ? "bg-gray-50" : "bg-white"}>
                    <td className="px-2 py-1 text-primary">{l.app_part_number || "—"}</td>
                    <td className="px-2 py-1">{l.part_number}</td>
                    <td className="px-2 py-1 font-sans">{l.description}</td>
                    <td className="px-2 py-1 text-center">{l.quantity}</td>
                    <td className="px-2 py-1 text-right">${(l.unit_cost || 0).toFixed(2)}</td>
                    <td className="px-2 py-1 text-right font-bold">${(l.total || l.quantity * l.unit_cost || 0).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Totals */}
            <div className="flex flex-col items-end gap-1 text-[10px] font-sans">
              <div className="flex gap-8 text-gray-500"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div>
              <div className="flex gap-8 text-gray-500"><span>GST (10%)</span><span>${gst.toFixed(2)}</span></div>
              <div className="flex gap-8 bg-gray-900 text-white font-bold px-3 py-1.5 rounded-sm mt-1 text-xs">
                <span>TOTAL (inc GST)</span><span>${total.toFixed(2)}</span>
              </div>
            </div>

            {/* Footer */}
            <div className="mt-6 pt-3 border-t border-gray-200 bg-gray-900 text-gray-400 text-[8px] px-3 py-2 rounded-sm -mx-1">
              <div>{COMPANY.name} · {COMPANY.address}, {COMPANY.city} {COMPANY.state} {COMPANY.postcode}</div>
              <div>Ph: {COMPANY.phone} · {COMPANY.email} · {COMPANY.website}</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 border-t border-border flex justify-end gap-3 flex-shrink-0">
          <Button variant="outline" onClick={onClose} className="rounded-sm font-heading text-xs uppercase tracking-wider">Close</Button>
          <Button onClick={generatePDF} className="bg-primary text-black font-heading font-semibold uppercase text-xs tracking-wider hover:bg-primary/90 rounded-sm">
            <Printer className="w-4 h-4 mr-1" /> Download PDF
          </Button>
        </div>
      </div>
    </div>
  );
}